animals:
 - "fox"
 - "goose"
 - "bear"
 - "camel"
 - "lama"
 - "cow"
 - "dog"
 - "cat"
 - "horse"
 - "frog"
 - "donkey"
 - "monkey"
 - "duck"
 - "tiger"
 - "crocodile"
 - "lizard"
 - "lion"
 - "squirrel"
 - "ant"
 - "whale"
 - "dolphin"
 - "ladybug"
 - "raven"
 - "rabbit"
 - "pigeon"
 - "penguin"
 - "spider"
 - "butterfly"
 - "elephant"
 - "zebra"
 - "wolf"
 - "eel"
 - "bee"
 - "wasp"
 - "jellyfish"
 - "chameleon"
 - "bat"
 - "snake"
 - "deer"
 - "pig"
 - "sheep"
 - "chicken"
 - "goat"